### ISSUE TITLE
on desktop - not clear where to use your mouse to swipe

### ISSUE THREAD

**Issue by sckott** [LucyMcGowan/contributr#4]
maybe a hint about where to click - i think only in the top part works, yes?

**Comment by LucyMcGowan** [comment]
I *think* any part of the card should be swipe-able but I have only tried this on a mac - what happens when you try to swipe the middle of the card?

**Comment by sckott** [comment]
ah, you're right!  looks like anywhere does work 

for reference: tested on chrome  56.0.2924.87
