### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by maelle** [LucyMcGowan/contributr#5]
* https://github.com/nstrayer/shinyswipr

* https://github.com/MarkEdmondson1234/googleID

* I think all other packages were on CRAN

**Comment by maelle** [comment]
Well that's for people trying to make it run locally and I realize I can't anyway (because of the Dropbox tokens) 😁

**Comment by LucyMcGowan** [comment]
I've added a readme with instructions to get the dropbox token (and the non-CRAN package installations) - do you think we need details on contributing too? it'd be fun if the community that uses this ends up contributing to it!

**Comment by maelle** [comment]
Yes and we could even have beginner issues, it'd be so meta 😁 after all the contributors will probably have an opinion on the way the starting guide is written for instance. But this is not a package so even if there is a list of ctb it'd be less cool than CRAN maybe.
